spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UangTsui/nav-config.git
          username:
          password:
          basedir: /Users/uangtsui/IdeaProjects/nav/nav-config/basedir
  rabbitmq:
    host: 192.168.2.107
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" # 配置刷新配置文件接口，访问地址（POST请求）：http://localhost:8080/actuator/bus-refresh
server:
  port: 8082