spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/UangTsui/nav-config.git
          # git仓库的账号（私有库必填）
          username:
          # git仓库的密码（私有库必填）
          password:
          basedir: /Users/uangtsui/IdeaProjects/nav/nav-config/basedir
      # 配置git仓库的分支
      label: master
  rabbitmq:
    host: 192.168.2.107
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 关闭安全认证
management:
  security:
    enabled: false
  # refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
server:
  port: 8082