spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/UangTsui/nav-config
          username: xxxxxx@qq.com
          password: password
          basedir: /Users/uangtsui/IdeaProjects/nav/nav-config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/